# Generated by Django 3.1.7 on 2021-03-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20210304_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
