# Generated by Django 3.1.7 on 2021-03-29 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20210309_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date',
        ),
    ]
