# Generated by Django 3.1.7 on 2021-03-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_vacation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
