# Generated by Django 3.1.7 on 2021-03-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='duration',
        ),
    ]
