# Generated by Django 3.1.7 on 2021-03-25 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='duration',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='vacation',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
