# Generated by Django 3.1.7 on 2021-03-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
