# Generated by Django 3.1.7 on 2021-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_auto_20210325_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
