# Generated by Django 3.1.7 on 2021-03-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_auto_20210308_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='duration',
        ),
    ]
