# Generated by Django 3.1.7 on 2021-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_vacation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_to',
            field=models.DateField(),
        ),
    ]
