# Generated by Django 3.1.7 on 2021-04-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_auto_20210401_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job_position',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
