# Generated by Django 3.1.7 on 2021-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_auto_20210329_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
