# Generated by Django 3.1.7 on 2021-03-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0005_auto_20210322_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date_from',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_to',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='duration',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
