# Generated by Django 3.1.7 on 2021-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0008_remove_vacation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
