# Generated by Django 3.1.7 on 2021-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0009_auto_20210322_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
