# Generated by Django 3.1.7 on 2021-03-08 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210309_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepagemodel',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
