# Generated by Django 3.1.7 on 2021-03-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210309_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepagemodel',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
