# Generated by Django 3.1.7 on 2021-03-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20210309_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepagemodel',
            old_name='employee',
            new_name='user',
        ),
    ]
