# Generated by Django 3.1.7 on 2021-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20210313_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
