# Generated by Django 3.1.7 on 2021-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20210305_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
