# Generated by Django 3.1.7 on 2021-03-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_auto_20210309_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
       # migrations.RenameField(
        #    model_name='vacations',
         #   old_name='User',
          #  new_name='user',
        #),
    ]
