# Generated by Django 3.1.7 on 2021-03-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_auto_20210307_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecontent',
            name='date_of_birth',
        ),
    ]
