# Generated by Django 3.1.7 on 2021-03-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.RenameField(
            model_name='profilecontent',
            old_name='user',
            new_name='employee',
        ),
    ]
