# Generated by Django 3.1.7 on 2021-03-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0005_auto_20210309_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecontent',
            old_name='employee',
            new_name='user',
        ),
    ]
