# Generated by Django 3.1.7 on 2021-03-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0007_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecontent',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
