# Generated by Django 3.1.7 on 2021-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0008_profilecontent_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontent',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
