# Generated by Django 3.1.7 on 2021-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0009_auto_20210314_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
