# Generated by Django 3.1.7 on 2021-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Vacation', '0002_auto_20210316_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
