# Generated by Django 3.1.7 on 2021-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20210303_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
    ]
