# Generated by Django 3.1.7 on 2021-03-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_auto_20210307_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
