# Generated by Django 3.1.7 on 2021-03-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_vacationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationdetail',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacationdetail',
            name='date_to',
            field=models.DateTimeField(),
        ),
    ]
