# Generated by Django 3.1.7 on 2021-03-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_auto_20210308_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacationDetail',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
    ]
