# Generated by Django 3.1.7 on 2021-03-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_vacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='vacation_desc',
            new_name='description',
        ),
    ]
