# Generated by Django 3.1.7 on 2021-03-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0009_auto_20210312_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='duration',
        ),
    ]
