# Generated by Django 3.1.7 on 2021-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_remove_vacation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
