# Generated by Django 3.1.7 on 2021-03-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0018_auto_20210317_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
