# Generated by Django 3.1.7 on 2021-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0019_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_position',
            field=models.CharField(max_length=255),
        ),
    ]
