# Generated by Django 3.1.7 on 2021-03-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0022_auto_20210317_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='profilepicture',
        ),
    ]
