# Generated by Django 3.1.7 on 2021-03-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0026_auto_20210321_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilepicture',
            new_name='profile_pic',
        ),
    ]
