# Generated by Django 3.1.7 on 2021-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0027_auto_20210322_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='datefrom',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateto',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
