# Generated by Django 3.1.7 on 2021-04-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0030_auto_20210420_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
