# Generated by Django 3.1.5 on 2021-03-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
