# Generated by Django 3.1.5 on 2021-03-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacations', '0002_auto_20210315_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_pic',
            field=models.ImageField(default='static/images/image1.jpeg', upload_to=''),
        ),
    ]
