# Generated by Django 3.1.5 on 2021-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacations', '0004_auto_20210324_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_pic',
            field=models.ImageField(default='Vacations/static/images/df.png', upload_to=''),
        ),
    ]
