# Generated by Django 3.1.7 on 2021-03-07 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalapp', '0002_vacation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacation',
            new_name='VacationInfo',
        ),
    ]
