# Generated by Django 3.1.7 on 2021-03-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_auto_20210318_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationinfo',
            name='datefrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacationinfo',
            name='dateto',
            field=models.DateField(),
        ),
    ]
