# Generated by Django 3.1.7 on 2021-03-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0011_auto_20210320_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationinfo',
            name='datefrom',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationinfo',
            name='dateto',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationinfo',
            name='description',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationinfo',
            name='duration',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
