# Generated by Django 3.1.7 on 2021-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_auto_20210320_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
