# Generated by Django 3.1.7 on 2021-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0013_auto_20210321_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
