# Generated by Django 3.1.7 on 2021-03-05 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Employee',
            new_name='Employee_Profile',
        ),
    ]
