# Generated by Django 3.1.7 on 2021-03-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_auto_20210314_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_vacation',
            old_name='datetime_from',
            new_name='Datetime_From',
        ),
        migrations.RenameField(
            model_name='employee_vacation',
            old_name='datetime_to',
            new_name='Datetime_To',
        ),
        migrations.RenameField(
            model_name='employee_vacation',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='employee_vacation',
            old_name='duration',
            new_name='Duration',
        ),
    ]
