# Generated by Django 3.1.7 on 2021-03-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0013_auto_20210317_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_profile',
            old_name='id',
            new_name='id1',
        ),
    ]
