# Generated by Django 3.1.7 on 2021-03-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0016_auto_20210320_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee_vacation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
