# Generated by Django 3.1.7 on 2021-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0019_auto_20210328_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_vacation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
